;;; leim-list.el -- list of LEIM (Library of Emacs Input Method) -*-coding: utf-8;-*-
;;
;; This file is automatically generated.
;;
;; This file contains a list of LEIM (Library of Emacs Input Method)
;; methods in the same directory as this file.  Loading this file
;; registers all the input methods in Emacs.
;;
;; Each entry has the form:
;;   (register-input-method
;;    INPUT-METHOD LANGUAGE-NAME ACTIVATE-FUNC
;;    TITLE DESCRIPTION
;;    ARG ...)
;; See the function `register-input-method' for the meanings of the arguments.
;;
;; If this directory is included in `load-path', Emacs automatically
;; loads this file at startup time.

(register-input-method
 "armenian" "Armenian" 'quail-use-package
 "Հ" "A transliteration scheme for Armenian characters."
 "quail/armenian")
(register-input-method
 "avestan-script" "Avestan Script" 'quail-use-package
 "𐬀" "A transliteration scheme for Avestan Script."
 "quail/avestan-script")
(register-input-method
 "avestan-trans" "Avestan Script" 'quail-use-package
 "ā̊" "A transliteration scheme for Avestan Transliteration."
 "quail/avestan-trans")
(register-input-method
 "glagolitic" "Glagolitic" 'quail-use-package
 "Ⰰ" "A transliteration scheme for Glagolitic characters."
 "quail/glagolitic")
(register-input-method
 "gothic" "Gothic" 'quail-use-package
 "𐌰" "A transliteration scheme for Gothic"
 "quail/gothic")
(register-input-method
 "old-persian" "Old Persian" 'quail-use-package
 "𐎠" "A transliteration scheme for Old Persian characters."
 "quail/old-persian")
(register-input-method
 "oscan" "Oscan" 'quail-use-package
 "𐌀𐌚" "A transliteration scheme for Oscan characters."
 "quail/oscan")
(register-input-method
 "pie" "Proto-Indo-European" 'quail-use-package
 "" "A transliteration scheme for Proto-Indo-European"
 "quail/pie")
(register-input-method
 "polytonicgreek" "Greek" 'quail-use-package
 "ἀ" "A transliteration scheme for Greek characters."
 "quail/polytonicgreek")
(register-input-method
 "pie" "Proto-Indo-European" 'quail-use-package
 "" "A transliteration scheme for Proto-Indo-European"
 "quail/vedic-deva")
(register-input-method
 "vedic-hk" "Vedic - Harvard-Kyoto" 'quail-use-package
 "" "A transliteration scheme for Vedic Sanskrit from HK to IAST."
 "quail/vedic-hk")
