(add-to-list 'load-path "~/.doom.d/lisp/pie-macs/leim/quail")
(require 'armenian)
(require 'vedic-hk)
(require 'pie)
(require 'glagolitic)
(require 'avestan-trans)
(require 'avestan-script)
(require 'old-persian)
(require 'oscan)
(require 'gothic)

(provide 'pie-macs)
