;;;
;;; Old Persian: An Old Persian transliteration scheme for emacs.
;;;
;;; AUTHOR: Caio Aguida 
;;; EMAIL: caioaguida@protonmail.com
;;; TWITTER: @silenus32
;;;


(require 'quail)
(quail-define-package
 "old-persian" "Old Persian" "𐎠" nil
 "A transliteration scheme for Old Persian characters."
 nil t t t t nil nil nil nil nil t)

(quail-define-rules
    ("a"    "𐎠")
    ("i"    "𐎡")
    ("u"    "𐎢")
    ("k"    "𐎣")
    ("ku"   "𐎤")
    ("x"    "𐎧")
    ("xi"   "𐎧")
    ("xu"   "𐎧")
    ("g"    "𐎥")
    ("gu"   "𐎦")
    ("c"    "𐎨")
    ("ç"    "𐏂")
    ("j"    "𐎩")
    ("ji"   "𐎪")
    ("t"    "𐎫")
    ("ti"   "𐎫")
    ("tu"   "𐎬")
    ("th"    "𐎰")
    ("d"    "𐎭")
    ("di"   "𐎮")
    ("du"   "𐎯")
    ("p"    "𐎱")
    ("f"    "𐎳")
    ("b"    "𐎲")
    ("n"    "𐎴")
    ("ni"   "𐎴")
    ("nu"   "𐎵")
    ("m"    "𐎶")
    ("mi"   "𐎷")
    ("mu"   "𐎸")
    ("y"    "𐎹")
    ("v"    "𐎺")
    ("vi"   "𐎻")
    ("r"    "𐎼")
    ("ri"   "𐎽")
    ("l"    "𐎾")
    ("s"    "𐎿")
    ("z"    "𐏀")
    ("š"    "𐏁")
    ("h"    "𐏃")
    ("ahuramazda1" "𐏈")
    ("ahuramazda2" "𐏉")
    ("ahuramazda3" "𐏊")
    ("xshayathia" "𐏋")
    ("dahyaus1" "𐏌")
    ("dahyaus2" "𐏌")
    ("baga" "𐏎")
    ("bumis" "𐏏")
    ("1" "𐏑")
    ("2" "𐏒")
    ("5" "𐏒𐏒𐏑")
    ("7" "𐏒𐏒𐏒𐏑")
    ("8" "𐏒𐏒𐏒𐏒")
    ("9" "𐏒𐏒𐏒𐏒𐏑")
    ("10" "𐏓")
    ("12" "𐏓𐏒")
    ("13" "𐏓𐏒𐏑")
    ("14" "𐏓𐏒𐏒")
    ("15" "𐏓𐏒𐏒𐏑")
    ("18" "𐏓𐏒𐏒𐏒𐏒")
    ("19" "𐏓𐏒𐏒𐏒𐏒𐏑")
    ("20" "𐏔")
    ("22" "𐏔𐏒")
    ("23" "𐏔𐏒𐏑")
    ("25" "𐏔𐏒𐏒𐏑")
    ("26" "𐏔𐏒𐏒𐏒")
    ("27" "𐏔𐏒𐏒𐏒𐏑")
    ("40" "𐏔𐏔")
    ("60" "𐏔𐏔𐏔")
    ("120" "𐏕𐏔")
)

(provide 'old-persian)
